# Generated by Django 4.2 on 2023-04-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='title',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
