# Generated by Django 4.2 on 2023-04-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_tasklist_title_tasklist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='name',
            new_name='title',
        ),
    ]
