# Generated by Django 4.2 on 2023-04-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_name_tasklist_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='title',
            new_name='name',
        ),
    ]
