# Generated by Django 4.2 on 2023-04-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_title_tasklist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.BooleanField(null=True),
        ),
    ]
