# Generated by Django 4.2 on 2023-04-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_remove_notification_task_notification_group_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='group_task',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='members',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_task',
        ),
    ]
