# Generated by Django 4.2 on 2023-04-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_remove_notification_group_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.grouptask'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.usertask'),
        ),
    ]
