# Generated by Django 4.2 on 2023-04-23 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_notification_group_task_notification_user_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='group_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.grouptask'),
        ),
    ]
