# Generated by Django 4.2 on 2023-04-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_daily_report_at_myuser_notification_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='daily_report_at',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='notification_before',
            field=models.IntegerField(default=0),
        ),
    ]
