# Generated by Django 4.2 on 2023-04-23 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_myuser_daily_report_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='daily_report_at',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
