# Generated by Django 4.2 on 2023-04-23 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_myuser_daily_report_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='daily_report_at',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
