# Generated by Django 4.2 on 2023-04-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_myuser_daily_report_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user_groups',
        ),
    ]
