# Generated by Django 4.2 on 2023-04-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_myuser_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygroup',
            name='notification_before',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='notification_before',
            field=models.IntegerField(default=1),
        ),
    ]
